# Generated by Django 4.2.30 on 2026-05-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='extra_bed',
            field=models.BooleanField(default=False),
        ),
    ]
