# Generated by Django 4.2.30 on 2026-05-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_extra_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of guests staying in the room (for admin records)'),
        ),
    ]
