# Generated by Django 4.2.30 on 2026-06-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_invoice_description_invoice_guest_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='breakdown',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
