# Generated by Django 4.2.30 on 2026-06-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_invoice_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='guest_gst_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
