# Generated by Django 4.2.30 on 2026-05-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='address',
            field=models.TextField(default=1, help_text='Compulsory physical address of the room/unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='extra_bed',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
    ]
