# Generated by Django 4.2.30 on 2026-05-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_address_room_extra_bed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Standard', 'Standard')], default='Standard', max_length=20),
        ),
    ]
