# Generated by Django 4.2.30 on 2026-05-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Cleaning', 'Cleaning'), ('Maintenance', 'Maintenance'), ('Blocked', 'Blocked')], default='Available', max_length=20),
        ),
    ]
