# Generated by Django 4.2.30 on 2026-05-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_room_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'ordering': ['amenity_type', 'name'], 'verbose_name_plural': 'amenities'},
        ),
        migrations.AddField(
            model_name='amenity',
            name='amenity_type',
            field=models.CharField(choices=[('General', 'General'), ('Technical', 'Technical')], default='General', max_length=20),
        ),
    ]
