# Generated by Django 4.2.30 on 2026-08-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_amenity_options_amenity_amenity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Premium', 'Premium')], default='Standard', max_length=20),
        ),
    ]
