# Generated by Django 4.2.30 on 2026-05-07 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='full_name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Name must be 3-200 characters and contain only letters and spaces', regex='^[a-zA-Z\\s]{3,200}$')]),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
