# Generated by Django 4.2.30 on 2026-05-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_alter_guest_full_name_alter_guest_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='address',
            field=models.TextField(default='Not Provided', help_text="Guest's physical address"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='extra_bed',
            field=models.BooleanField(default=False, help_text='Whether an extra bed is requested'),
        ),
    ]
