# Generated by Django 4.2.30 on 2026-05-07 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_guest_address_guest_extra_bed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='address',
            field=models.TextField(help_text="Guest's physical address", validators=[django.core.validators.RegexValidator(message='Address must be at least 10 characters long and contain valid characters.', regex='^[a-zA-Z0-9\\s,.-]{10,500}$')]),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone must include country code followed by 10 digits (e.g., +919876543210).', regex='^\\+\\d{1,3}\\d{10}$')]),
        ),
    ]
