# Generated by Django 4.2.30 on 2026-05-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_alter_guest_address_alter_guest_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='id_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
