# Generated by Django 4.2.30 on 2026-05-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(default='My Hotel', max_length=200)),
                ('check_in_time', models.TimeField(default='14:00')),
                ('check_out_time', models.TimeField(default='11:00')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('cancellation_policy', models.TextField(default='All cancellations are handled by the hotel team. Please contact us directly.')),
                ('guest_email_template', models.TextField(default='Dear {{guest_name}},\n\nThank you for booking with us!\n\nBooking Reference: {{booking_reference}}\nRoom: {{room_name}}\nCheck-in: {{check_in}}\nCheck-out: {{check_out}}\nTotal Amount: ₹{{total_amount}}\n\nWe look forward to welcoming you.\n\nWarm regards,\nThe Hotel Team')),
                ('admin_email_template', models.TextField(default='New Booking Alert!\n\nReference: {{booking_reference}}\nGuest: {{guest_name}}\nRoom: {{room_name}}\nCheck-in: {{check_in}}\nCheck-out: {{check_out}}\nTotal: ₹{{total_amount}}')),
                ('admin_email_address', models.EmailField(default='admin@hotel.com', max_length=254)),
            ],
            options={
                'verbose_name': 'Hotel Settings',
                'verbose_name_plural': 'Hotel Settings',
            },
        ),
    ]
