# Generated by Django 4.2.30 on 2026-05-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_alter_hotelsettings_admin_email_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsettings',
            name='hotel_address',
            field=models.TextField(default='1, Karaya Rayappa, Thevar Street, Sulur, Coimbatore - 641402'),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='hotel_email',
            field=models.EmailField(default='sriaskresidency@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='hotel_phone',
            field=models.CharField(default='+91 9444551122', max_length=20),
        ),
        migrations.AlterField(
            model_name='hotelsettings',
            name='check_in_time',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AlterField(
            model_name='hotelsettings',
            name='check_out_time',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AlterField(
            model_name='hotelsettings',
            name='hotel_name',
            field=models.CharField(default='Sri ASK Residency', max_length=200),
        ),
    ]
