# Generated by Django 4.2.30 on 2026-06-08 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_hotelsettings_hotel_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelsettings',
            name='check_in_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AlterField(
            model_name='hotelsettings',
            name='check_out_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
